# Generated by Django 3.1.7 on 2021-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210405_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='blog_app/images/%Y/%m/%d/'),
        ),
    ]
